services:
  sandstorm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandstorm
    network_mode: host
    security_opt:
      - seccomp:unconfined
      - systempaths=unconfined
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    env_file:
      - .env
    # uncomment environment section to install / update the game server on container start
    # when updating or installing the game server, run only one container to avoid conflicts
    # e.g. docker compose up sandstorm
    # environment: 
    #   - RUN_APP_UPDATE=true
    volumes:
      - ./server:/home/steam/server
      - ./server-content:/home/steam/server/Insurgency/Content
      - ./mod.io:/home/steam/mod.io
      - ./config-inis/EngineCheckpoint.ini:/home/steam/server/Insurgency/Saved/Config/LinuxServer/_Engine.ini
      - ./config-inis/GameCheckpoint.ini:/home/steam/server/Insurgency/Saved/Config/LinuxServer/_Game.ini
      - ./config-txts:/home/steam/server/Insurgency/Config/Server
      - ./start.sh:/home/steam/server/start.sh
  sandstorm-zombie:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandstorm-zombie
    network_mode: host
    security_opt:
      - seccomp:unconfined
      - systempaths=unconfined    
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./server-zombie:/home/steam/server
      - ./server-content:/home/steam/server/Insurgency/Content
      - ./mod.io:/home/steam/mod.io
      - ./config-inis/EngineZombie.ini:/home/steam/server/Insurgency/Saved/Config/LinuxServer/_Engine.ini
      - ./config-inis/GameZombie.ini:/home/steam/server/Insurgency/Saved/Config/LinuxServer/_Game.ini
      - ./config-txts:/home/steam/server/Insurgency/Config/Server
      - ./start_zombie.sh:/home/steam/server/start.sh
  sandstorm-zombie-frenzy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandstorm-zombie-frenzy
    network_mode: host
    security_opt:
      - seccomp:unconfined
      - systempaths=unconfined    
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./server-zombie-frenzy:/home/steam/server
      - ./server-content:/home/steam/server/Insurgency/Content
      - ./mod.io:/home/steam/mod.io
      - ./config-inis/EngineZombieFrenzy.ini:/home/steam/server/Insurgency/Saved/Config/LinuxServer/_Engine.ini
      - ./config-inis/GameZombieFrenzy.ini:/home/steam/server/Insurgency/Saved/Config/LinuxServer/_Game.ini
      - ./config-txts:/home/steam/server/Insurgency/Config/Server
      - ./start_zombie_frenzy.sh:/home/steam/server/start.sh
  sandstorm-restarter:
    image: docker:cli
    container_name: sandstorm-restarter
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    environment:
      RESTART_TIME: 20:30
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        echo "Server will restart at $${RESTART_TIME} UTC time every day."
        while true; do
          echo "Current time: $$(date +'%H:%M')"
          if [ "$$(date +'%H:%M')" = "$${RESTART_TIME}" ]; then
            echo "Restarting containers..."
            docker restart sandstorm 
            docker restart sandstorm-zombie
            docker restart sandstorm-zombie-frenzy
          fi
          sleep 60
        done