# Complete config for reference because Insurgency removes commented line when starting the server.

[/Script/Engine.GameNetworkManager]
bMovementTimeDiscrepancyDetection=false
bMovementTimeDiscrepancyResolution=false

[/Script/Insurgency.INSGameMode]
bKillFeed=True
bKillFeedSpectator=True
bKillerInfo=True
bKillerInfoRevealDistance=True
bEnforceFriendlyFireReflect=False
TeamKillLimit=5
TeamKillGrace=0.2
TeamKillReduceTime=90

[/Script/Insurgency.INSMultiplayerMode]
bRestrictClassByPlayerLevel=false
GameStartingIntermissionTime=5
PreRoundTime=5
PostRoundTime=10
PostGameTime=10
bAllowFriendlyFire=True
FriendlyFireModifier=0.5
FriendlyFireReflect=0
bMapVoting=True
bUseMapCycle=False
RoundLimit=3
WinLimit=1
InitialSupply=25
MaximumSupply=25
IdleLimit=180
IdleLimitLowReinforcements=90
IdleCheckFrequency=30

[/Script/Insurgency.INSCoopMode]
bUseVehicleInsertion=True
MaxPlayersToScaleEnemyCount=4
bSupportsSoloWaves=True
bLoseWhenAllPlayersDead=True
SpawnProtectionTime=2
bSoloGame=False
bBotsUseHumanLoadouts=True

[/CapBotCount/Mutators/CapCount.CapCount_C]
Max=100
OverflowRatioAllowed=0.0
MilitiaOverflowAllowed=1.0

# CHECKPOINT
[/Script/Insurgency.INSCheckpointGameMode]
AIDifficulty=1
bForceSoloWaves=True
SoloWaves=2
SoloReinforcementTime=15
SoloWaveIncrementOnObjectiveCapture=2
MinimumEnemies=10
MaximumEnemies=40
ObjectiveTotalEnemyRespawnMultiplierMin=3
ObjectiveTotalEnemyRespawnMultiplierMax=3
RespawnDPR=0
RespawnDelay=3
CounterAttackRespawnDPR=0
CounterAttackRespawnDelay=3
FinalCacheBotQuotaMultiplier=1
SoloRoundTime=900
bCounterAttackReinforce=True
DefendTimer=120
DefendTimerFinal=180

[/CounterStall/Mutators/StallCounter.StallCounter_C]
bForceRecaptureTimer=True
MinDelay=60
MaxDelay=60

# Small Maps
[/Headshots/Mutators/HealthyFrenzy.HealthyFrenzy_C]
BotHealthMultiplier=1.25
PlayerHealthMultiplier=1

# Large Maps    
[/Headshots/Mutators/Healthy.Healthy_C]
BotHealthMultiplier=1.875
PlayerHealthMultiplier=1

# SMALL, 8 / player
[/CountMutators/Mutators/Small.Small_C]
MinEnemies=8
MaxEnemies=32
RespawnDPR=0
RespawnDelay=3
CounterAttackRespawnDPR=0
CounterAttackRespawnDelay=3

# MID, 10 / player, primary mutator for zombie
[/CountMutators/Mutators/Mid.Mid_C]
MinEnemies=10
MaxEnemies=40
RespawnDPR=0
RespawnDelay=3
CounterAttackRespawnDPR=0
CounterAttackRespawnDelay=3

# BIG, 12 / player
[/CountMutators/Mutators/Big.Big_C]
MinEnemies=12
MaxEnemies=48
RespawnDPR=0
RespawnDelay=3
CounterAttackRespawnDPR=0
CounterAttackRespawnDelay=3

[/MoreAmmoPlus/Mutators/MoreAmmoPlus.MoreAmmoPlus_C]
; PrimaryAmmoMultiplys=1
; SecondaryAmmoMultiplys=1
UnderbarrelAmmoMultiplys=3
ExplosiveLauncherAmmoMultiplys=3

[/MoreAmmo/Mutators/MoreAmmo.MoreAmmo_C]
PrimaryAmmoMultiplier=2
SecondaryAmmoMultiplier=2
; UnderbarrelAmmoMultiplier=1.0
; ExplosiveLauncherAmmoMultiplier=1.0

[/Reloads/Mutator/BP_Mutator_Reloads.BP_Mutator_Reloads_C]
SpeedChoice=Fastest
ExcludeWeaponType=Assault Rifle
ExcludeWeaponType=Light Machine Gun
# ExcludeWeaponType=Bolt Rifle
ExcludeWeaponType=Marksman Rifle
ExcludeWeaponType=Carbine
# ExcludeWeaponType=Shotgun
ExcludeWeaponType=Automatic Shotgun
ExcludeWeaponType=Submachine Gun
ExcludeWeaponType=Pistol
ExcludeWeaponType=Launcher
ExcludeWeaponType=Single Launcher
ExcludeWeaponType=Heavy Machine Gun
# ExcludeWeaponType=Revolver

[/AwardRespawns/Mutators/AwardWaves.AwardWaves_C]
InitialWaves=2
MinThreshold=50
MaxThreshold=150
MinWaveIncOnObjective=1
MaxWaveIncOnObjective=1
bEnableMessaging=False
PrintEvery=5
# END CHECKPOINT ZOMBIE

[/Script/AIModule.AIController]
bAdvancedTactics=True

[/Script/AIModule.AISenseConfig_Hearing]
HearingRange=4000 ;768
LoSHearingRange=6000 ;1500

[/Script/AIModule.AISenseConfig_Sight]
SightRadius=9000 ;3000
LoseSightRadius=20000 ;3500
PeripheralVisionAngleDegrees=180
AutoSuccessRangeFromLastSeenLocation=150 ;500

[/ImprovedAI/Mutators/ImprovedAI_2.ImprovedAI_2_C]
bScaleAIDifficulty=False
PlayerCountForMinAIDifficulty=1
PlayerCountForMaxAIDifficulty=8
MinAIDifficulty=1
MaxAIDifficulty=1
HearAwareDistanceGunshot=19900.0 ;6000.0
BotSpawnMethod=ClosestToObjective
bCustomBotNames=False